Overwatch={
        "Ana":[["3","3","3"], "https://overwatch.fandom.com/wiki/Ana"],
        "Baptiste":[["3","2","2"], "https://overwatch.fandom.com/wiki/Baptiste"],
        "Brigitte":[["1","2","1"], "https://overwatch.fandom.com/wiki/Brigitte"],
        "Lucio":[["3","3","2"], "https://overwatch.fandom.com/wiki/Lucio"],
        "Mercy":[["2","2","3"], "https://overwatch.fandom.com/wiki/Mercy"],
        "Moira":[["2","3","2"], "https://overwatch.fandom.com/wiki/Moira"],
        "Symmetra":[["3","1","2"], "https://overwatch.fandom.com/wiki/Symmetra"],
        "Zenyatta":[["2","2","2"], "https://overwatch.fandom.com/wiki/Zenyatta"],
        "Doomfist":[["1","1","3"], "https://overwatch.fandom.com/wiki/Doomfist"],
        "Genji":[["1","1","3"], "https://overwatch.fandom.com/wiki/Genji"],
        "McCree":[["3","1","3"], "https://overwatch.fandom.com/wiki/Cassidy"],
        "Pharah":[["2","1","2"], "https://overwatch.fandom.com/wiki/Pharah"],   
        "Reaper":[["1","3","1"], "https://overwatch.fandom.com/wiki/Reaper"],
        "Soldier76":[["1","1","2"], "https://overwatch.fandom.com/wiki/Soldier:76"],
        "Sombra":[["1","3","3"], "https://overwatch.fandom.com/wiki/Sombra"],
        "Tracer":[["1","2","2"], "https://overwatch.fandom.com/wiki/Tracer"],
        "Bastion":[["3","1","1"], "https://overwatch.fandom.com/wiki/Bastion"],
        "Hanzo":[["2","1","3"], "https://overwatch.fandom.com/wiki/Hanzo"],
        "Junkrat":[["3","2","3"], "https://overwatch.fandom.com/wiki/Junkrat"],
        "Mei":[["2","3","3"], "https://overwatch.fandom.com/wiki/Mei"],
        "Torbjörn":[["2","1","1"], "https://overwatch.fandom.com/wiki/Torbjörn"],  
        "Widowmaker":[["1","1","3"], "https://overwatch.fandom.com/wiki/Widowmaker"],  
        "Ashe":[["2","3","3"], "https://overwatch.fandom.com/wiki/Ashe"],
        "D.Va":[["1","2","3"], "https://overwatch.fandom.com/wiki/D.Va"],      
        "Orisa": [["3","2","1"], "https://overwatch.fandom.com/wiki/Orisa"],
        "Reinhardt":[["2","2","1"], "https://overwatch.fandom.com/wiki/Reinhardt"],   
        "Roadhog":[["1","1","1"], "https://overwatch.fandom.com/wiki/Roadhog"],     
        "Hammond" :[["1","3","2"], "https://overwatch.fandom.com/wiki/Hammond"], 
        "Winston":[["3","3","1"], "https://overwatch.fandom.com/wiki/Winston"],
        "Zarya":[["2","3","1"], "https://overwatch.fandom.com/wiki/Zarya"],
    }